version: '3'

services:
  db:
    image: postgres
    container_name: ps01
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - /Projects/mtest-v1/src:/src
      - /Projects/mtest-v1/config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && gunicorn mtest_app.wsgi -b 0.0.0.0:8000"
    volumes:
       - /Projects/mtest-v1/src:/src
    expose:
      - "8000"
    depends_on: 
      - db
  