# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtestdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='mtestdata',
            name='mid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
