# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0002_auto_20161122_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtestdata',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
