# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0003_auto_20161123_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtestdata',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
