# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0005_auto_20161123_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtestdata',
            name='mid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
