# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0006_auto_20161128_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtestdata',
            name='mid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
