# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0009_auto_20161128_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='mtestdata',
            name='mid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mtestdata',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='zob',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
