# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0010_auto_20161201_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dia',
            options={'verbose_name': 'Procedure', 'verbose_name_plural': 'Procedures'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.AlterModelOptions(
            name='zob',
            options={'verbose_name': 'Duty', 'verbose_name_plural': 'Duties'},
        ),
    ]
